### ISSUE TITLE
Outdated

### ISSUE THREAD

**Issue by NoSpread** [vsetka/deepl-translator#7]
**NOTE:** Before creating an issue please make sure you are using the latest version of `deepl-translator`.

## The problem

Bug / Outdated after deepL API updated

## What is the current behavior?

You can't translate anything.

`undefined:1
<html>
^

SyntaxError: Unexpected token < in JSON at position 0
    at JSON.parse (<anonymous>)
    at IncomingMessage.res.on (E:\Bibliothek\Dokumente\Atom\Node\DeepL\node_modules\deepl-translator\src\request-helper.js:10:40)
    at IncomingMessage.emit (events.js:187:15)
    at endReadableNT (_stream_readable.js:1090:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)`

## Environment

Node v10.3.0
deepL-translator 1.2.0

**Comment by vsetka** [comment]
Thanks for reporting. I don’t have access to a computer right now, but I’ll try to have a look at it later today.
